### ISSUE TITLE
Обнаруженные баги

### ISSUE THREAD

**Issue by aizenbit** [aizenbit/Mary-s-Turinga#1]
- [x] Если нажать на Debug, а затем на Stop, программа вылетает
- [x] Если выйти за левый край ~~бесконечной~~ ленты, программа вылетает
- [x] Скорее всего, если выйти за правый край, тоже будет неловко

**Comment by NuclearHound** [comment]
- [x] Комбинация Start/Pause + Stop тоже дает вылет
